/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ottobite (https://sketchfab.com/ottobite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-hacked-pc-sketchfabweeklychallenge-192ab9d4706f4ffaaf22f9a299289d75
Title: Stylized Hacked PC #SketchfabWeeklyChallenge
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hackeroom = (props) =>  {
  const { nodes, materials } = useGLTF('models/glb.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 1.75, -0.1, -1.35]} scale={21.276596}>
        <mesh
          name="Final_lambert1_0"
          castShadow
          receiveShadow
          geometry={nodes.Final_lambert1_0.geometry}
          material={materials.lambert1}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/glb.glb')
export default Hackeroom
